import { User, Post, Friendship, Notification, Comment } from './types.ts';

// In-Memory Seed Storage for Instant Prototyping and Production Demonstration
export const mockUsers: User[] = [
  {
    id: 'usr_alex',
    username: 'alex_rivers',
    email: 'alex@example.com',
    role: 'ADMIN',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      userId: 'usr_alex',
      displayName: 'Alex Rivers',
      bio: 'Staff Systems Architect. Working on high-availability distributed graphs and fast resilient databases.',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      coverUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
      location: 'San Francisco, CA',
      websiteUrl: 'https://alexrivers.dev',
      friendsCount: 3,
      postsCount: 2,
    },
  },
  {
    id: 'usr_sarah',
    username: 'sarah_chen',
    email: 'sarah@example.com',
    role: 'VERIFIED_CREATOR',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      userId: 'usr_sarah',
      displayName: 'Sarah Chen',
      bio: 'Product Designer & Visual Storyteller. Exploring tactile UI and high-density information systems.',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
      coverUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
      location: 'Seattle, WA',
      websiteUrl: 'https://sarahchen.design',
      friendsCount: 3,
      postsCount: 2,
    },
  },
  {
    id: 'usr_marcus',
    username: 'marcus_vance',
    email: 'marcus@example.com',
    role: 'USER',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      userId: 'usr_marcus',
      displayName: 'Marcus Vance',
      bio: 'Marathon runner, specialty coffee enthusiast, and venture builder in Austin.',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      coverUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&auto=format&fit=crop&q=80',
      location: 'Austin, TX',
      websiteUrl: 'https://marcusvance.me',
      friendsCount: 2,
      postsCount: 1,
    },
  },
  {
    id: 'usr_elena',
    username: 'elena_rostova',
    email: 'elena@example.com',
    role: 'USER',
    status: 'ACTIVE',
    emailVerified: true,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    profile: {
      userId: 'usr_elena',
      displayName: 'Elena Rostova',
      bio: 'Architectural historian & writer. Exploring concrete brutalism and civic spaces.',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
      coverUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&auto=format&fit=crop&q=80',
      location: 'Brooklyn, NY',
      websiteUrl: 'https://elenarostova.substack.com',
      friendsCount: 2,
      postsCount: 1,
    },
  },
];

export const mockFriendships: Friendship[] = [
  {
    id: 'fr_1',
    requesterId: 'usr_alex',
    addresseeId: 'usr_sarah',
    status: 'ACCEPTED',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'fr_2',
    requesterId: 'usr_alex',
    addresseeId: 'usr_marcus',
    status: 'ACCEPTED',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'fr_3',
    requesterId: 'usr_sarah',
    addresseeId: 'usr_elena',
    status: 'ACCEPTED',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'fr_4',
    requesterId: 'usr_elena',
    addresseeId: 'usr_alex',
    status: 'PENDING',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

export const mockComments: Record<string, Comment[]> = {
  post_1: [
    {
      id: 'comm_1',
      postId: 'post_1',
      authorId: 'usr_sarah',
      content: 'Did you evaluate CRDT state convergence latency versus leader lease consensus for this layout?',
      reactionsCount: 2,
      createdAt: new Date(Date.now() - 3 * 3600000).toISOString(),
      author: {
        id: 'usr_sarah',
        username: 'sarah_chen',
        displayName: 'Sarah Chen',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
      },
      replies: [
        {
          id: 'comm_2',
          postId: 'post_1',
          authorId: 'usr_alex',
          parentCommentId: 'comm_1',
          content: 'We opted for state-based CRDTs for timeline events and Raft for transactional leader writes. Best combination of speed and deterministic correctness!',
          reactionsCount: 3,
          createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
          author: {
            id: 'usr_alex',
            username: 'alex_rivers',
            displayName: 'Alex Rivers',
            avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
          },
        },
      ],
    },
  ],
  post_2: [
    {
      id: 'comm_3',
      postId: 'post_2',
      authorId: 'usr_elena',
      content: 'The mist filtering through the pine canopy in that second frame is breathtaking! What lens focal length was that?',
      reactionsCount: 1,
      createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
      author: {
        id: 'usr_elena',
        username: 'elena_rostova',
        displayName: 'Elena Rostova',
        avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
      },
    },
  ],
};

export const mockPosts: Post[] = [
  {
    id: 'post_1',
    authorId: 'usr_alex',
    content: 'Just deployed our new geo-distributed replication topology across 3 edge clusters. Zero replication lag during regional failover simulation tests!',
    mediaUrls: [],
    linkPreview: {
      title: 'Monotonic Read Guarantees in Partitioned Networks',
      description: 'An architectural analysis of consensus trade-offs and bounded staleness in modern distributed storage.',
      url: 'https://distributed-systems.org/article',
      image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    },
    visibility: 'PUBLIC',
    reactionsCount: 12,
    commentsCount: 2,
    sharesCount: 3,
    isPinned: true,
    createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    author: {
      id: 'usr_alex',
      username: 'alex_rivers',
      displayName: 'Alex Rivers',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
      role: 'ADMIN',
    },
    currentUserReaction: 'LOVE',
  },
  {
    id: 'post_2',
    authorId: 'usr_sarah',
    content: 'Early morning hike along the Pacific coast ridge. The light breaking through coastal maritime fog produces the most serene natural gradients.',
    mediaUrls: [
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1000&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1000&auto=format&fit=crop&q=80',
    ],
    visibility: 'PUBLIC',
    reactionsCount: 28,
    commentsCount: 1,
    sharesCount: 5,
    isPinned: false,
    createdAt: new Date(Date.now() - 8 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 3600000).toISOString(),
    author: {
      id: 'usr_sarah',
      username: 'sarah_chen',
      displayName: 'Sarah Chen',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
      role: 'VERIFIED_CREATOR',
    },
    currentUserReaction: 'LIKE',
  },
  {
    id: 'post_3',
    authorId: 'usr_marcus',
    content: 'Completed 20 miles along Lady Bird Lake trail in Austin. Humidity was 85%, but the cadence stayed steady at 178 SPM. Final block before taper week!',
    mediaUrls: [
      'https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=1000&auto=format&fit=crop&q=80',
    ],
    visibility: 'FRIENDS_ONLY',
    reactionsCount: 15,
    commentsCount: 0,
    sharesCount: 1,
    isPinned: false,
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    author: {
      id: 'usr_marcus',
      username: 'marcus_vance',
      displayName: 'Marcus Vance',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
      role: 'USER',
    },
  },
  {
    id: 'post_4',
    authorId: 'usr_elena',
    content: 'Observing structural honesty in central library architecture: exposed board-formed concrete and deep skylights designed to minimize glare while inviting natural daylight.',
    mediaUrls: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1000&auto=format&fit=crop&q=80',
    ],
    visibility: 'PUBLIC',
    reactionsCount: 19,
    commentsCount: 0,
    sharesCount: 2,
    isPinned: false,
    createdAt: new Date(Date.now() - 48 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 48 * 3600000).toISOString(),
    author: {
      id: 'usr_elena',
      username: 'elena_rostova',
      displayName: 'Elena Rostova',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
      role: 'USER',
    },
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif_1',
    recipientId: 'usr_alex',
    actorId: 'usr_elena',
    type: 'FRIEND_REQUEST',
    isRead: false,
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    actor: {
      id: 'usr_elena',
      username: 'elena_rostova',
      displayName: 'Elena Rostova',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    },
    message: 'sent you a friend request.',
  },
  {
    id: 'notif_2',
    recipientId: 'usr_alex',
    actorId: 'usr_sarah',
    type: 'POST_COMMENT',
    entityId: 'post_1',
    isRead: true,
    createdAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    actor: {
      id: 'usr_sarah',
      username: 'sarah_chen',
      displayName: 'Sarah Chen',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    },
    message: 'commented on your post: "Did you evaluate CRDT state..."',
  },
  {
    id: 'notif_3',
    recipientId: 'usr_alex',
    actorId: 'usr_marcus',
    type: 'POST_REACTION',
    entityId: 'post_1',
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    actor: {
      id: 'usr_marcus',
      username: 'marcus_vance',
      displayName: 'Marcus Vance',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    },
    message: 'reacted with 👍 to your post.',
  },
];
